apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: web-color
    namespace: argocd
  spec:
    destination:
      namespace: web-color-argocd
      server: https://kubernetes.default.svc
    project: web-color-argocd
    source:
      path: k8s
      repoURL: https://github.com/MacmillerMartins/treinamento-argocd.git
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
      automated:
        selfHeal: true
        prune: true
kind: List
metadata:
  resourceVersion: ""